spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fornecedor
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
